{
 "title": "Electoral District Dashboard - E Poll Book",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "electoral_district_name",
    "label": "District",
    "query": "SELECT DISTINCT(Name_EN) FROM ElectoralDistricts;"
   },
   {
    "name": "electoral_district_id",
    "query": "SELECT ID FROM ElectoralDistricts WHERE Name_EN = N${electoral_district_name:singlequote} ;"
   },
   {
    "name": "casted_votes",
    "query": "SELECT Count(*) \nFROM VoteRecords\nWHERE DistrictID = ${electoral_district_id} and VotingStatus = \"VOTED\" and $__timeFilter(Timestamp);\n\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Polling Division",
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 0 },
   "content": "\n<div style=\"text-align:center\"><span style=\"color:#73BF69;font-weight: bold\">${electoral_district_name} </span></div>",
   "targets": [
    { "rawSql": "\n  \n" }
   ]
  },
  {
   "title": "Casted Votes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT Count(*) as \"Casted Votes\"\nFROM VoteRecords\nWHERE $__timeFilter(Timestamp) and DistrictID = ${electoral_district_id} and VotingStatus = \"VOTED\";\n"
    }
   ]
  },
  {
   "title": "Registered Voters",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(ElectorID) AS \"Registered Voters\"\nFROM ElectorRegistry\nWHERE DistrictID = ${electoral_district_id};\n"
    }
   ]
  },
  {
   "title": "Voter Distribution Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(Timestamp,$__interval),\n  count(ID) AS \"Vote Count\"\nFROM VoteRecords\nWHERE\n   $__timeFilter(Timestamp) and DistrictID = ${electoral_district_id} and VotingStatus = \"VOTED\"\nGROUP BY 1\nORDER BY $__timeGroup(Timestamp,$__interval)"
    }
   ]
  },
  {
   "title": "Gender Statistics",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT (COUNT(*)/${casted_votes}) * 100 as \"Male Voters (%)\"\nFROM ElectorRegistry\nWHERE Sex = 'MALE' and ID in (SELECT ID FROM VoteRecords WHERE DistrictID = ${electoral_district_id} and VotingStatus = \"VOTED\");"
    },
    {
     "rawSql": "SELECT (COUNT(*)/${casted_votes}) * 100 as \"Female Voters (%)\"\nFROM ElectorRegistry\nWHERE Sex = \"FEMALE\" and ID in (SELECT ID FROM VoteRecords WHERE DistrictID = ${electoral_district_id} and VotingStatus = \"VOTED\");"
    }
   ]
  },
  {
   "title": "Male Voter Distribution Over Age",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT concat(10*floor(Age/10), '-', 10*floor(Age/10) + 10) as \"range\",  count(*) as value, current_timestamp AS time\nFROM (\n      SELECT v.ID,Sex,Age\n      FROM VoteRecords as v\n      INNER JOIN ElectorRegistry ON v.ID = ElectorRegistry.ID\n\t    WHERE v.DistrictID = ${electoral_district_id} and \n\t    v.VotingStatus = \"VOTED\" and v.Age != -1 and Sex = \"MALE\" and $__timeFilter(Timestamp)) as t\ngroup by `range`\nORDER BY Age ASC;"
    }
   ]
  },
  {
   "title": "Female Voter Distribution Over Age",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT concat(10*floor(Age/10), '-', 10*floor(Age/10) + 10) as \"range\",  count(*) as value, current_timestamp AS time\nFROM (\n      SELECT v.ID,Sex,Age\n      FROM VoteRecords as v\n      INNER JOIN ElectorRegistry ON v.ID = ElectorRegistry.ID\n\t    WHERE v.DistrictID = ${electoral_district_id} and  \n\t    v.VotingStatus = \"VOTED\" and v.Age != -1 and Sex = \"FEMALE\" and $__timeFilter(Timestamp)) as t\ngroup by `range`\nORDER BY Age ASC;"
    }
   ]
  }
 ]
}